media:
  input: public
  output: /
content:
  - name: chumps
    label: Chumps
    type: collection
    path: src/content/chumps
    fields:
      - { name: name, label: Name, widget: "string" }
      - { name: slug, label: Slug, type: string }
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd
      # - { name: date_chump, default: 1, label: "Order of chump on a given day", widget: "number", value_type: "int" }
      - name: date_chump
        label: "Order of chump on a given day"
        type: number
      - { name: thanks, default: "temp", label: Thanks, widget: "string" }
      - { name: url, default: "temp", label: URL, widget: "string" }
      - name: image
        label: Image
        type: image
        list: false
        options:
          path: src/content/chumps/images
          extensions: [ jpg, jpeg, png, gif, webm ]


