media:
  input: public
  output: /
content:
  - name: chumps
    label: Chumps
    type: collection
    path: src/content/chumps
    fields:
      - { name: name, label: Name, widget: "string" }
      - { name: slug, label: Slug, type: string }
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd
      - name: date_chump
        label: "Order of chump on a given day"
        type: number
      - { name: thanks, default: "temp", label: Thanks, widget: "string" }
      - { name: url, default: "temp", label: URL, widget: "string" }
      - name: image
        label: Image
        type: image
        list: false
        options:
          path: src/content/chumps/images
          extensions: [ jpg, jpeg, png, gif, webm ]
          
  - name: events
    label: Events
    type: collection
    path: src/content/events
    fields:
      - { name: title, label: Title, type: string, required: true }
      - name: date
        label: Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: event_type
        label: Event Type
        type: select
        required: true
        options:
          values: [ Chump, News, MajorEvent, Era ]
      - { name: slug, label: Slug, type: string }
      - { name: thanks, default: "temp", label: Thanks, widget: "string" }
      - name: body
        label: Body
        type: rich-text
      - name: media
        label: Media
        type: object
        list: true
        required: false
        fields:
          - { name: caption, label: Caption, type: string, required: true }
          - { name: ismain, label: Is Main Media?, type: boolean, required: true }
          - name: media_type
            label: Media Type
            type: select
            required: true
            default: image
            options:
              values: [ image, video ]
          - name: image
            label: Image
            type: image
            list: false
            required: false
            options:
              path: public/images/events/
              extensions: [ jpg, jpeg, png, gif, webp ]
          - name: video_file
            label: Video File
            type: file
            list: false
            required: false
            options:
              path: public/videos/events/
              extensions: [ mp4, webm, mov, avi ]
          - name: video_url
            label: Video URL (YouTube/Vimeo/etc.)
            type: string
            required: false
          - name: body
            label: Body
            type: rich-text